// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // roda via node (nao ts-node) porque o Prisma Client gerado usa
    // imports estilo NodeNext (".js" apontando pro ".ts") que o ts-node
    // nao resolve sozinho - precisa estar compilado primeiro (npm run build)
    seed: "node dist/prisma/seed.js",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
